complete -c ersec -l help -d 'Show help'
complete -c ersec -l version -d 'Show version'
complete -c ersec -l self-test -d 'Run offline self-test'
complete -c ersec -l capabilities -d 'Show capabilities'
complete -c ersec -l roadmap-audit -d 'Audit roadmap coverage'
complete -c ersec -l build-assurance -d 'Run build assurance'
complete -c ersec -l build-assurance-out -d 'Write build assurance JSON'
complete -c ersec -l browser -d 'Enable browser discovery'
complete -c ersec -l profile -d 'Scan profile'
